### ISSUE TITLE
Link in Privacy Policy (Redirection issue and clarification)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#100]
Module/Page: Dashboard's Settings
Specific Feature: Privacy Policy
Test Cases: Click the "**here**" link in the Privacy Policy modal
Expected Results: **_Should redirect to somewhere else (where user can manage their account settings) or just in the dashboard?_**
Actual Results: Redirect to Dashboard and in the dashboard (QR code gone, Login and Register appear on header, Type of Account disappears, Sidebar  disappears)
Supporting File:
This is the link inside the Privacy Policy Modal.
![image](https://user-images.githubusercontent.com/54056737/88505681-5c94f780-d002-11ea-95d9-6b6c63679512.png)

It redirects to the Dashboard and this is how the dashboard looks like after clicking the link.
![image](https://user-images.githubusercontent.com/54056737/88508458-14c59e80-d009-11ea-85e8-4ecb756f9da8.png)

This is to show after clicking the "Scan QR" button
![image](https://user-images.githubusercontent.com/54056737/88506189-91ee1500-d003-11ea-88e7-d971e7233615.png)

**Comment by PN25-RicaChristine** [comment]
This problem was tested in all type of account and results are the same.

**Comment by GarridoL** [comment]
This is already resolved.

**Comment by PN25-RicaChristine** [comment]
@LGarrido0708 Checked on local. Already redirect to profile page but "privacy policy" model does not closes.

**Comment by PN25-RicaChristine** [comment]
Issue fixed on local not yet on live.
@LGarrido0708  Already checked on your local. It's working good. Successfully redirects to profile page and closes "privacy policy" modal.

**Comment by PN25-RicaChristine** [comment]
> @LGarrido0708 Checked on local. Already redirect to profile page but "privacy policy" model does not closes.

8/111/2020
Upon latest live update this issue occurs again @LGarrido0708  redirect to profile page but "privacy policy" model does not closes.

**Comment by GarridoL** [comment]
@PN25-RicaChristine It's not yet merged. Update pa nako si sir nga naa koy giusab gamay.

**Comment by PN25-RicaChristine** [comment]
@GarridoL  can you reopen this issue? since wla pmn ni sa live. thank you. ill be the one to reclose this if fixed na sa live.

**Comment by PN25-RicaChristine** [comment]
8/18/2020

Fixed on live and working
