### ISSUE TITLE
Emptied Search engine doesn't display list of patient's info

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#101]
Module/Page: Patients
Specific Feature: Search 
Test Cases: Emptying Search engine
Expected Results: Back to the list of complete patient's info in table.
Actual Results: Same information is displayed after searching.

* The **sort by** is in dropdown but there's no other option being shown it could be a label?
* For adding new patient for suggestion it could be better to use add instead of new as it is much clearer of what is the main purpose of this button which is to add new patient. Thanks

![image](https://user-images.githubusercontent.com/54094859/88508915-86561a80-d012-11ea-970d-814d4446d399.png)

**Comment by aeromellaure31** [comment]
pwede rmn cguro ni ENTER lng ang gamiton maong wlay button gibutang

**Comment by jalandoni** [comment]
> pwede rmn cguro ni ENTER lng ang gamiton maong wlay button gibutang

yes it works, the issue now is when the search engine is being emptied, the same data was displayed  instead of the rest in list of other patient's info in table.
