### ISSUE TITLE
Pagination not working in Patients page

### ISSUE THREAD

**Issue by LEulin** [kennCK/tinabangay#103]
Module/Page: Dashboard
Specific Feature: Patients 
Test Cases: (Pagination/dropdown no use) Click dropdown/pagination
Expected Results: Loads to another list/set of data
Actual Results: the data are not loading to another lists of data
Supporting File: 
![image](https://user-images.githubusercontent.com/54056461/88509399-93273e00-d013-11ea-8502-cb846f2b23fb.png)

**Comment by rLaurentePn2k19** [comment]
@LEulin 
![image](https://user-images.githubusercontent.com/54059621/88642138-afe67300-d0f2-11ea-9a86-d1b6b944ba13.png)

The pagination is working, as I check it on my local.

**Comment by Claire-pn** [comment]
![image](https://user-images.githubusercontent.com/54086974/88644556-b1656a80-d0f5-11ea-8cdc-173f02d0ee51.png)
