### ISSUE TITLE
Add visited places enhancement to view &Delete button 

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#104]
Module/Page:  Patient (Brgy_Agency & Agency_Gov)
Specific Feature: view visited places & delete button in table action
Test Cases: Viewing visited places and delete button
Expected Results: Noticeable view to added info and a pop up modal to confirm before deleting data.
Actual Results: After the visited places is added the area where information being displayed is not noticeable for most users.
And also the delete button don't have a confirmation that might cause trouble if it the icon is accidentally click.

![image](https://user-images.githubusercontent.com/54094859/88523881-3cc5f980-d02b-11ea-82be-2e029e4ccd8e.png)

**Comment by rLaurentePn2k19** [comment]
Done ni sya.

**Comment by rLaurentePn2k19** [comment]
Close #104

**Comment by rLaurentePn2k19** [comment]
@themonstrousdev , can you see the previous comment if correct siya nga comment sa pag close. Wa kaayo mi ka klaro if comment or commit to imu ge ingon a while ago sa meeting. Thanks 👍

**Comment by themonstrousdev** [comment]
> @themonstrousdev , can you see the previous comment if correct siya nga comment sa pag close. Wa kaayo mi ka klaro if comment or commit to imu ge ingon a while ago sa meeting. Thanks 👍

Sa commit message na cya, Rangie, dili comment. Ig commit ninyo sa inyong fix kay inyong commit message "Closes #104" or "Fixes #104"

**Comment by rLaurentePn2k19** [comment]
> > @themonstrousdev , can you see the previous comment if correct siya nga comment sa pag close. Wa kaayo mi ka klaro if comment or commit to imu ge ingon a while ago sa meeting. Thanks 👍
> 
> Sa commit message na cya, Rangie, dili comment. Ig commit ninyo sa inyong fix kay inyong commit message "Closes #104" or "Fixes #104"

Sige Elle, salamat I will inform nalang the others.
