### ISSUE TITLE
Object displayed in the HTML form

### ISSUE THREAD

**Issue by Claire-pn** [kennCK/tinabangay#108]
Module/Page: Invitation 
Specific Feature: invitation form
Test Cases: filling a valid  email address
Expected Results: Invitation sent.
Actual Results: { "status": 100, "message": { "code": [ "The code field is required." ] } }
![image](https://user-images.githubusercontent.com/54086974/88518436-12703e00-d023-11ea-8ca8-b5f7e56d199d.png)
![image](https://user-images.githubusercontent.com/54086974/88520893-cb844780-d026-11ea-8313-45114d5ff57d.png)
![image](https://user-images.githubusercontent.com/54086974/88761000-d4992400-d1a0-11ea-8ece-898b4ef1e503.png)

**Comment by GarridoL** [comment]
Laure is currently working on this issue.

**Comment by GarridoL** [comment]
Done.

**Comment by Claire-pn** [comment]
@GarridoL  ipaOpen ni ug balik laine since dli pa okay sa live heheh
