### ISSUE TITLE
Symptoms Reporting Advanced Date Acceptance Issue

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#109]
Module/Page: Symptoms Reporting
Specific Feature: Report Symptom Date Field
Test Cases: Input or Select and Submitted an Advanced Date Value
Expected Results: **Should not accept or cannot select** any date that is after the actual date of reporting or submitting the symptoms 
Actual Results: Accepts any date (advance and not) but mislabeled date. Advance date is still labeled as "days ago" (but in terms of list, it is still from earliest to latest)
Supporting File:
Current or Actual date of submitting is July 27,2020 but I input or select that the symptoms happens on July 30,2020 (which is 3 days advanced)
![image](https://user-images.githubusercontent.com/54056737/88519410-48f68a80-d01c-11ea-9abb-8b04b3fdbc88.png)
And this is how it looks like after submitting with the respective inputs shown above.
![image](https://user-images.githubusercontent.com/54056737/88522244-4b5ae380-d020-11ea-8336-cc56a593c270.png)
 
**SUGGESTION**: The users  **should not be able to select or submit an advanced date value** of reporting their symptoms because it is unpredictable that they'll get sick on that specific date in the future.

**Comment by LGarrido0708** [comment]
@Lalaine

**Comment by PN25-RicaChristine** [comment]
@LGarrido0708  solve nani but wla pa online ang changes

**Comment by GarridoL** [comment]
> @LGarrido0708 solve nani but wla pa online ang changes

It's okay. Just make sure to test this on local.

**Comment by Pathran-phantom1823** [comment]
@PN25-RicaChristine  Already Done

**Comment by PN25-RicaChristine** [comment]
Already fixed and enhanced on local but not yet online.
@LGarrido0708  Already checked on @Pathran-phantom1823 local. It's fixed and enhanced.
REMARKS:
- Can select advanced date but does not submit report. Shows an alert that "Date is advanced" when submitted  with any date that is after the actual date of reporting or submitting the symptoms
- Both Date and Select type of Symptoms has (*****) to show that it's required. 
- Displays an error message "**Oops! Fields with (*) are required**" if both required field are empty or either of the required field is unselected or empty.

**Comment by PN25-RicaChristine** [comment]
New symptoms reporting on live accepts advance date. @LGarrido0708  @Pathran-phantom1823

**Comment by PN25-RicaChristine** [comment]
@LGarrido0708  and @Pathran-phantom1823  New symptoms reporting updated on live ACCEPTS ADVANCED DATE
![image](https://user-images.githubusercontent.com/54056737/89262520-e9bafa80-d659-11ea-86ec-2ecd0a9ff1bc.png)

**Comment by PN25-RicaChristine** [comment]
8/10/2020

Upon latest live update, this is fixed and working
