### ISSUE TITLE
"Accept & Register Now!" Button Redirection Page(Referral notification via Email)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#110]
Module/Page: Signup Page
Specific Feature: Registration Form
Test Cases: Click "**Accept & Register Now!**"  in the referral notification sent via email
![image](https://user-images.githubusercontent.com/54056737/88525239-8b23ca00-d024-11ea-8f98-183f93b60b0b.png)
Expected Results: Should Redirect to Signup page
Actual Results: Redirected to a page where there's no registration form
![image](https://user-images.githubusercontent.com/54056737/88525717-25840d80-d025-11ea-93c7-951ee0976908.png)

**Comment by GarridoL** [comment]
@

**Comment by PN25-RicaChristine** [comment]
this is fixed on live.
redirection page:
![image](https://user-images.githubusercontent.com/54056737/89150276-6aa9c180-d588-11ea-86e8-bfc364eed7bf.png)
