### ISSUE TITLE
Submitting location (Web)

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#111]
Module/Page: (Brgy_Agency, Agency_Gov & business) Locations
Specific Feature: Add location
Test Cases: Clicking submit button in google autocomplete location along with pin and use location button
Expected Results: After clicking submit location will be successfully added to displayed addresses in location  page.
Actual Results: Unable to submit location 

![image](https://user-images.githubusercontent.com/54094859/88616022-a692e180-d0c5-11ea-9851-c8acb2659492.png)

**Comment by Pathran-phantom1823** [comment]
@kennCK  sir guba man daw ni ingon c kent
