### ISSUE TITLE
Success and Error Message applied on Updating Info

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#116]
Module/Page: (Agency_Gov & Brgy_agency) Settings
Specific Feature: Update 
Test Cases1: Clicking update button without any changes in the inputs
Test Cases2: Clicking update button with empty field.
Expected Results1: Error message stating that there is no changes being applied.
Expected Results2: Error message stating to fill in the designated field.
Actual Results1: Still successfully updated
Actual Results2: Still successfully updated and invalid email address

![image](https://user-images.githubusercontent.com/54094859/88652198-12dd0780-d0fd-11ea-8048-3a9e1721d37d.png)
![image](https://user-images.githubusercontent.com/54094859/88655182-fcd14600-d100-11ea-80e6-72c646d37418.png)

**Comment by GarridoL** [comment]
@rLaurentePn2k19 you've been assigned to this issue

**Comment by rLaurentePn2k19** [comment]
@LGarrido0708  This is done, but nag wait pako sa merged confirmation ni Ken.
