### ISSUE TITLE
Suggestion: Add "Remove/Delete" Button for images in profile section

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#118]
Module/Page: Profile Page
Specific Features: Profile Picture List of Images
Suggestions: Add "Remove/Delete" button for user's can delete or remove **unnecessary** images (_as shown below, encircled with red pen_) they have uploaded.
![image](https://user-images.githubusercontent.com/54056737/88772302-c6500580-d1aa-11ea-890f-5482607043ba.png)
Additional:
- Same as "Apply" Button, user will just select an image and then click the "Remove/Delete" button.
- When "Remove/Delete" button is clicked ,an alert modal will pop up if user will surely delete the image or not (optional)

**Comment by GarridoL** [comment]
@rLaurentePn2k19

**Comment by Pathran-phantom1823** [comment]
@LGarrido0708  almost done

**Comment by PN25-RicaChristine** [comment]
This issue is fixed already on local not yet online.
@rLaurentePn2k19  already checked and tested on your local. Very good enhancement.

**Comment by PN25-RicaChristine** [comment]
8/4/2020
Updated changes already on live and is working. @rLaurentePn2k19
