### ISSUE TITLE
Search engine for profile images displays nothing

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#119]
Module/Page: Profile Page
Specific Features: Search field in "Images" Modal
Test Cases: 
_(**_Blue pen mark on below files are the images that should be displayed with its respective test case._**)_

TEST 1:
- Type first character which uploaded images on list has 
![image](https://user-images.githubusercontent.com/54056737/88777976-167e9600-d1b2-11ea-8ce6-3e0accf1a6ab.png)
 Below is the actual result after press "Enter"
![image](https://user-images.githubusercontent.com/54056737/88775682-32346d00-d1af-11ea-8d95-681a89cb3687.png)

TEST 2:
- Type "name_of_file.extension" of an existing image on the list 
![image](https://user-images.githubusercontent.com/54056737/88775964-90615000-d1af-11ea-938d-1355a6ab8d2d.png)
 Below is the actual result after press "Enter"
![image](https://user-images.githubusercontent.com/54056737/88776067-b129a580-d1af-11ea-9f8f-63d76040c92f.png)

TEST 3:
- Type "name_of_file" without extension of an existing image on list 
![image](https://user-images.githubusercontent.com/54056737/88776202-e0401700-d1af-11ea-9546-fd2d8add3a21.png)
 Below is the actual result after press "Enter"
![image](https://user-images.githubusercontent.com/54056737/88776289-f9e15e80-d1af-11ea-94ee-5098052a22b3.png)

TEST 4:
- Type "name_of_file.extension" which is not on the list 
![image](https://user-images.githubusercontent.com/54056737/88776835-afacad00-d1b0-11ea-88f7-cc66066ef5d0.png)
 Below is the actual result after press "Enter"
![image](https://user-images.githubusercontent.com/54056737/88776957-e2ef3c00-d1b0-11ea-9987-30f95fea5dee.png)

TEST 5:
- Type "name_of_file" without extension which is not on the list
![image](https://user-images.githubusercontent.com/54056737/88777544-893b4180-d1b1-11ea-9615-c328acb2f314.png)
 Below is the actual result after press "Enter"
![image](https://user-images.githubusercontent.com/54056737/88777078-031efb00-d1b1-11ea-8b6b-72b7587e6958.png)

Expected Results: 
- Should display all images whose file name starts with the letter
- Should display the specific image being searched (name_of_file.extension)
- Should display all images which has the same file_name regardless of extensions
- Should display some message like "No Results" to inform the user that this file don't exist
- Should display some message like "No Results" to inform the user that this file_name don't have any match

Actual Results: **ALL TEST CASES DISPLAYS NOTHING (EMPTY)**

**Comment by PN25-RicaChristine** [comment]
@rLaurentePn2k19  try to check on this again.

**Comment by GarridoL** [comment]
@PN25-RicaChristine

**Comment by PN25-RicaChristine** [comment]
@GarridoL ill try to check on live ling. i'll update lng

**Comment by PN25-RicaChristine** [comment]
8/18/20

working on local. its also working on live but the local file name of the image is not attached on the uploaded image
![image](https://user-images.githubusercontent.com/54056737/90477915-d0887280-e15e-11ea-9cd0-31c4ee9e91c7.png)
