### ISSUE TITLE
Unhide Answer Form

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#120]
Module/Page:  Scan QR code(temp_scanner)
Specific Feature: Scan Qr code with camera on web
Test Cases: Clicking Customer/checkin/checkout button in Answer Health Declaration Form (User without an assign barangay)
Expected Results: Hides the modal for Answer Health Declaration Form and back to the scanned account information details with the error message "Sorry, you do not have assigned location. Please contact your merchant" same as the Answer Health Declaration Form
Actual Results: Pop up modal didn't hide.

![image](https://user-images.githubusercontent.com/54094859/88787309-433ca880-d1c6-11ea-8544-30a21ba7eb0d.png)

result in send form

![image](https://user-images.githubusercontent.com/54094859/88787341-4c2d7a00-d1c6-11ea-9f62-12dc8651cc2e.png)

**Comment by Pathran-phantom1823** [comment]
@jalandoni  this is Done
