### ISSUE TITLE
"X" button on upper right corner of profile picture shows when setting's menu pop up

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#122]
Module/Page: Profile Page
Specific Features:"**X**" button on upper right corner of profile picture
Test Cases: Click settings icon on top
Expected Results: The "**X**" button on upper right corner of profile picture SHOULD NOT DISPLAY IN FRONT (should be behind) of setting's pop up menu
Actual Results: The "**X**" button on upper right corner of profile picture DISPLAYS IN FRONT of setting's pop up menu
Supporting File: 
![image](https://user-images.githubusercontent.com/54056737/88878600-804e7c80-d252-11ea-82de-dc23120568d5.png)

**Comment by GarridoL** [comment]
@rLaurentePn2k19

**Comment by PN25-RicaChristine** [comment]
Fixed on local but changes not yet live.
@rLaurentePn2k19 already checked on your local. It is already fixed. The "X" button on upper right corner of profile picture (is behind) does not display in front  of setting's pop up menu.

**Comment by PN25-RicaChristine** [comment]
This is fixed and changes already on live.

**Comment by PN25-RicaChristine** [comment]
8/10/2020

Upon latest live update on profile page , this issue appears again @rLaurentePn2k19 @LGarrido0708 . Guess this is due to the update made on profile information issue resolved by laure on #124 . same rmn ni sila ug module

**Comment by PN25-RicaChristine** [comment]
@GarridoL  can you reopen this issue? since ni occur nmn sd ni na issue sa live. thank you. ill be the one to reclose this if fixed na sa live.

**Comment by PN25-RicaChristine** [comment]
8/18/2020

Not yet fixed on live
