### ISSUE TITLE
Updating Profile Information Issues and Enhancement Suggestions

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#124]
Module/Page: Profile
Specific Features: Profile Form

1. Test Case:  All input fields are filled in with correct type of data or information(First Name,Last Name,Gender,Phone Number,Address,Birthdate)  and click "update" button
Expected Results: SHOULD DISPLAY A MESSAGE LIKE "Successfully Updated!" to verify that it was really updated.
Actual Results: Updated informations are saved but no notifications or message to verify that it was updated
Supporting file: 
![image](https://user-images.githubusercontent.com/54056737/88892082-6cb10f00-d26e-11ea-8a35-e44ad51ab527.png)
Suggestion: Add a message like "Successfully Updated!"

2. Test Case: Filled in incorrect type of data such as in Phone Number, Address and an exceed year for Datebirth but correct data on other fields , then click "update" button
Expected Results: SHOULD NOT update or submit information (SHOULD DISPLAY ERROR MESSAGE for Incorrect Type of Data, For the birth year the user should and can only select until the current year)
Actual Results: Informations still submitted and updated , no error message for incorrect type of data , any year can still be selected
Supporting file:
![image](https://user-images.githubusercontent.com/54056737/88893250-48563200-d270-11ea-8d20-8228f256554c.png)
Suggestions: 
- Phone Number: Though it is optional, the field should only accept digits (add phone number validation). 
- Address: Can add dropdown list for regions,provinces, municipalities, brgy. , Can also add an optional input field for sitio/building if user want to be specific with his address.
- Birthdate Year: It should not submit if user input a year that exceed the current year (add alert)

3. Test Case: Click "Update" Button with some unfilled fields (this is for updating the profile information for the first time) 
Expected Results: Profile  SHOULD NOT be updated unless all required fields are filled.
Actual Results: Informations still saved , no error message for supposed to be required field
Supporting file:
![image](https://user-images.githubusercontent.com/54056737/88898739-607d7f80-d277-11ea-874f-ae2729bd7099.png)

4. Test Case: Clears some filled datas and change other data fields then click " update" button (this is for user who have completely updated their informations before)
![image](https://user-images.githubusercontent.com/54056737/88900570-c23ee900-d279-11ea-9ca5-4ac73919c221.png)
Expected Results: Profile SHOULD NOT be updated unless all required fields are filled.
Actual Results: Changed data are updated, emptied field were back to previous data (as well as for _optional_ field that is emptied), no error message for supposed to be required field
Supporting File:
![image](https://user-images.githubusercontent.com/54056737/88901197-b273d480-d27a-11ea-859a-e7fb5a3afcb7.png)

5. Test Case: Emptied all fields , no changing of data, except for Gender, then click "Update" button  (this is for user who have  updated their informations before)
Expected Results: Profile SHOULD NOT be updated unless all required fields are filled.
Actual Results: All emptied fields were back to previous data (as well as for _optional_ field that is emptied), no error message for supposed to be required field
Supporting File:
![image](https://user-images.githubusercontent.com/54056737/88902874-f8319c80-d27c-11ea-8955-fe7e69d6cd7b.png)

**Comment by PN25-RicaChristine** [comment]
Here Rangie @rLaurentePn2k19

**Comment by GarridoL** [comment]
@PN25-RicaChristine Kindly check sa local ni Laure.

**Comment by PN25-RicaChristine** [comment]
@LGarrido0708  already checked on @mhineMhe laure's local everything is fixed except for updating phone number when it is emptied.
TEST CASE: Updating Personal Information by making the Phone Number (_optional_) empty.
EXPECTED RESULT: Information should still save and accept  changes on phone number even if it is empty or null since it is an optional field.
ACTUAL RESULT: Cannot save updated information (wherein phone number is emptied or unfilled)
![image](https://user-images.githubusercontent.com/54056737/89498863-41d43700-d7e9-11ea-999d-28a198735147.png)

**Comment by PN25-RicaChristine** [comment]
8/7/2020 Update: @LGarrido0708  On local (laure @mhineMhe) everything is fixed except for updating phone number when it is emptied.
TEST CASE: Updating Personal Information by making the Phone Number (optional) empty.
EXPECTED RESULT: Emptied phone number should be updated and saved empty.
ACTUAL RESULT: Successfully save changes when Phone Number (optional) is empty but  after saving it goes back to the previous data or number.
![image](https://user-images.githubusercontent.com/54056737/89621905-57666100-d8bc-11ea-847c-a72b87556ae2.png)

**Comment by PN25-RicaChristine** [comment]
8/10/2020

Checked on live: Fixed and working.
