### ISSUE TITLE
Enhancement:  Edit branch display

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#128]
Module/Page: Link accounts(Business)
Specific Feature: Edit branch
Test Cases: Clicking edit branch
Expected Results: Pop up modal that displays the old branch name to update.
Actual Results: Same pop up modal with the assigning of branch

![edit branch](https://user-images.githubusercontent.com/54094859/89022597-defc1f00-d354-11ea-8ebe-807c7363716f.PNG)

**Comment by Pathran-phantom1823** [comment]
@jalandoni its almost done need lang ug confirmation
