### ISSUE TITLE
Advance date in date of birth and history travel

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#130]
Module/Page: Form
Specific Feature: Filling in Form(Check in/out/customer)
Test Cases: Choosing date of birth and date of history travel
Expected Results: Can't choose advance date
Actual Results: Still can choose advance date basing on the current date.

![birthdate](https://user-images.githubusercontent.com/54094859/89024755-3223a100-d358-11ea-98a6-0e659bb8b249.png)

**Comment by aeromellaure31** [comment]
@kennCK pwede nako butangan og verification ang date if valid cya? Pra mas accurate.

**Comment by keyrwinz** [comment]
fixed in https://github.com/kennCK/tinabangay/pull/137

**Comment by keyrwinz** [comment]
please close once merged. thank you
