### ISSUE TITLE
Data not in  proper columns (ADD VISITED PLACE) and MISCALCULATIONS OF DATES

### ISSUE THREAD

**Issue by LEulin** [kennCK/tinabangay#139]
Module/Page: DASHBOARD (AGENCY_GOV, AGENCY_BRGY)
Specific Feature: Patients (ADD VISITED PLACE)
Test Cases: Click "Submit" button with filled in required fields ---> data are added to "visited place", click "location Icon" ---> visited places are displayed. 
Expected Results: Data should be in proper columns and date should be updated according to what date was inputted in the add visited place form. I expect that if I input in the date the day before today, it should display "yesterday" in the date visited column. (Date miscalculation is not only in visited place module but in all modules as well.)
Actual Results: Data are not in proper columns and the date is not updated in "date visited" column. (Miscalculation of dates.)
Supporting File: 
![Capture](https://user-images.githubusercontent.com/54056461/89392532-3c6ce300-d73c-11ea-919f-67f2d5ddb3e8.PNG)
![Capture2](https://user-images.githubusercontent.com/54056461/89392538-3ecf3d00-d73c-11ea-8766-6968eedbc5f8.PNG)
![image](https://user-images.githubusercontent.com/54056461/89393591-991ccd80-d73d-11ea-881c-16c582553466.png)

**Comment by LEulin** [comment]
@kennCK,
 Ken unsaon ni?

**Comment by LEulin** [comment]
This issue is both on local and live.

**Comment by themonstrousdev** [comment]
@keyrwinz Please ko check ani as this is probably the date_human sa API
