### ISSUE TITLE
Admin Dashboard Empty

### ISSUE THREAD

**Issue by HTundra** [kennCK/tinabangay#143]
Admin dashboard empty
![image](https://user-images.githubusercontent.com/58643990/89515564-e23a5380-d809-11ea-8a68-9a0a7c8bbe9b.png)

**Comment by themonstrousdev** [comment]
The same issue for AGENCY_BRGY. It should have more or less the same details as AGENCY_LGU
![image](https://user-images.githubusercontent.com/40906882/89611855-cfc72500-d8b0-11ea-8fc1-1d63019420f9.png)
