### ISSUE TITLE
Incomplete options of Actions  on linked accounts (without assignment and assigned branch)

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#165]
Module/Page: Linked_accounts
Specific Feature: Assigning the linked accounts 
Test Cases: Clicking dropdown Actions button to a certain link account without assignment and assigned branch yet. 
Expected Results: Display options of as assign as scanner, assign as business authorized, assign branch, edit address, delete
Actual Results: Only assign as business authorized and delete is displayed.
![image](https://user-images.githubusercontent.com/54094859/89765343-b7f9d600-db28-11ea-8f85-970c331574db.png)

**Comment by Pathran-phantom1823** [comment]
Done na ni Siya
