### ISSUE TITLE
Temp_scanner can't send hdf though scanned user is link to the merchant

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#173]
Module/Page: Scanned account
Specific Feature: Sending HDF to the link account of a certain merchant.
Test Cases: Sending HDF(employee checkin/out) to the link account
Expected Results: Successfully sent Health declaration form
Actual Results: Scanned user is not linked to the merchant.

![image](https://user-images.githubusercontent.com/54094859/90381128-83999300-e0af-11ea-9f64-5e208f458634.png)

![image](https://user-images.githubusercontent.com/54094859/90381730-5dc0be00-e0b0-11ea-91d7-cf30e2fe92cc.png)

![image](https://user-images.githubusercontent.com/54094859/89775638-d7016380-db3a-11ea-9822-6c54beaf23df.png)
![image](https://user-images.githubusercontent.com/54094859/89775815-2778c100-db3b-11ea-9616-be964d1abeaf.png)

**Comment by GarridoL** [comment]
@Patrick
