### ISSUE TITLE
Submitted "Cough"  Report DOES NOT ADD ON THE TABLE LIST of all  reported symptoms

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#176]
Module/Page: Symptoms Reporting
Specific Features: Symptoms Report Table/List
Test Cases: Click "Yes" button in the Confirmation modal with COUGH as submitted report
Expected Results: Should add and display the reported symptom in the table
Actual Results: Does not display the submitted symptom (even if the page is refreshed considering the slow connection but the outcome is still the same, tried testing this for 5 times, does not display the report. This change happens after the latest update when the  advance date is fixed).
Supporting File: IMAGE
The yellow highlight shows where the submitted symptom should be inserted.
![image](https://user-images.githubusercontent.com/54056737/89866975-08ce0500-dbe3-11ea-80b8-f683fa4933e4.png)

**Comment by GarridoL** [comment]
Really. Tried this on local and it's working.

**Comment by GarridoL** [comment]
@PN25-RicaChristine Working sad sa live. Just that you still need to refresh the page to retrieve all the data since they did not retrieve the data after creation, but we will work on that.

**Comment by PN25-RicaChristine** [comment]
@GarridoL  tried to check all symptoms and only COUGH cannot be added to list when submitted.
![image](https://user-images.githubusercontent.com/54056737/89875891-69177380-dbf0-11ea-8064-547e5a1273db.png)

**Comment by PN25-RicaChristine** [comment]
8/12/2020

fixed and enhanced in local (bargaso)

**Comment by PN25-RicaChristine** [comment]
reopened since not fixed on live. ill be the one to reclose this if ma check na nku na working sa live. thank you

**Comment by PN25-RicaChristine** [comment]
8/14/2020
Fixed and enhanced in live
