### ISSUE TITLE
Improve [Fixed] Table Column Width  (Symptoms Reports)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#185]
**Module/Page:** Symptoms Reporting Page
**Specific Features:** Symptoms Report Table
**Test Cases:** View symptoms report table from different account.
**Expected Results:** Table column width should be fixed no matter how long symptom's remarks are.
**Actual Results:**Table column varies from each account depend on the length of remarks submitted.
Supporting File: (All are ZOOM IN to 100%)
This column width is better.
![image](https://user-images.githubusercontent.com/54056737/90091328-a8f96a80-dd58-11ea-9cec-916d3132bc01.png)
While this two images is a bit unorganized to look at (though this does not affect app's functionality)
![image](https://user-images.githubusercontent.com/54056737/90091632-7e5be180-dd59-11ea-9abd-a6214585a426.png)
![image](https://user-images.githubusercontent.com/54056737/90091667-8ddb2a80-dd59-11ea-9225-e8938340a584.png)
_Suggestion_: Limit "remarks" character. If not, make the width of the table column in fixed measurement,

**Comment by GarridoL** [comment]
@Bargaso
