### ISSUE TITLE
Scrollable table for link accounts/retrieved employee and searched engine(Enhancement )

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#188]
Module/Page:Linked_accounts/Employee
Specific Features: Retrieved linked accounts in table
Test Cases: Viewing the retrieved accounts
Expected Results: For easy retrieved for the linked accounts table must be scrollable and search engine may do
**Actual Results:**You need to scroll down and find manually specific accounts or employee in checking purposes and it  would be time consuming especially if it will be in large number list of employee already.
![image](https://user-images.githubusercontent.com/54094859/90136026-1e3f5c80-dda6-11ea-8381-01e97a64c047.png)

**Comment by Pathran-phantom1823** [comment]
@jalandoni Done

**Comment by GarridoL** [comment]
@jalandoni This is done locally but making the table scrollable is not anymore necessary since naa nay pagination. Thank you.

**Comment by jalandoni** [comment]
@GarridoL noted, checking for updates. Thanks
