### ISSUE TITLE
Wrong Table Content in TEMP_SCANNER  linked_accounts page

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#209]
Module/Page: Linked_accounts page
Specific Features: linked_accounts page content (employee table)
Test Cases: Click Settings Icon > Employees
![image](https://user-images.githubusercontent.com/54056737/90726576-8a651780-e2f4-11ea-95e5-ff66b6a3e4bd.png)
Expected Results: TEMP_SCANNER employee table should not have **ACTIONS** that only business can/have, (such as remove or assign an account as temp_scanner,business authorized,assigning branch, edit address, and unlinking account)
Actual Results:TEMP_SCANNER employee table HAVE**ACTIONS**  (same actions with  business)
Supporting File: IMAGE
![image](https://user-images.githubusercontent.com/54056737/90727218-7ec62080-e2f5-11ea-94ef-34260885d02b.png)

**Comment by Pathran-phantom1823** [comment]
@PN25-RicaChristine  this is due to old data that was stored and database, sir kenn said, to just ignore that since they cannot touch the live data, also its just a test account that you used
