### ISSUE TITLE
Continue Button(Reset password page)

### ISSUE THREAD

**Issue by Claire-pn** [kennCK/tinabangay#63]
Test Case(s)
Input incorrect password(not alphanumeric)

Remarks:

Password successfully updated

**Comment by themonstrousdev** [comment]
Assigned to Rangie

**Comment by rLaurentePn2k19** [comment]
Done ni siya ate, pero dili ko ka test sa local. Kay I think dili man maka reset password basta sa local.

**Comment by rLaurentePn2k19** [comment]
@kennCK Sa increment diay ni nga root folder ang akoa ge modify, (scr/increment/basic). Ang Validation nga function akoa ge modify, pero according sa ila ni patrick dili daw e pa modify ang mga functions nga naa sa increment nga folder.
