### ISSUE TITLE
Sign-up button(WEB)

### ISSUE THREAD

**Issue by Claire-pn** [kennCK/tinabangay#65]
Test case:
Incorrect email and correct password,username
Sample: asdsad@sdfdf.sdfdf

Remarks:
Redirect to Request Consent

**Comment by themonstrousdev** [comment]
Assigned to Rangie

**Comment by rLaurentePn2k19** [comment]
![image](https://user-images.githubusercontent.com/54059621/88496641-6d3c7200-cff0-11ea-80b7-590919596541.png)

**Comment by rLaurentePn2k19** [comment]
@kennCK #89 and #65, has the same issue about the email. As I observed they used the same function in the services the ValidateEmail.
