### ISSUE TITLE
Mobile QA(forget Password issue)

### ISSUE THREAD

**Issue by cherry-pn** [kennCK/tinabangay#66]
forget your password issue with regards to sending the correct email to request change
![Screenshot_20200723_153504](https://user-images.githubusercontent.com/54086808/88264670-c3fb3080-ccfe-11ea-8aae-5141483bfc96.jpg)

**Comment by themonstrousdev** [comment]
@cherry-pn  please transfer this issue to https://www.github.com/kennCK/tinabangay_app
