### ISSUE TITLE
Unused Space(Web)

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#67]
![SCAN QR](https://user-images.githubusercontent.com/54094859/88266974-ba73c780-cd02-11ea-844c-dcf2ee3d8cf2.PNG)

**Comment by themonstrousdev** [comment]
**Details:**
When clicking the "Scan QR" button on a device with no camera, it will make space for a camera but not have anything to show on screen.

**Comment by jalandoni** [comment]
> **Details:**
> When clicking the "Scan QR" button on a device with no camera, it will make space for a camera but not have anything to show on screen.

Okay, yes we had tested it this time through laptop and it works since our desktop has no web cam while checking it yesterday. Thank you.
