### ISSUE TITLE
Invitation button(Invite friends page in USER/SCANNER account_WEB)

### ISSUE THREAD

**Issue by Claire-pn** [kennCK/tinabangay#69]
test case:
input a invalid email format

Remarks:
invitation sent

![email](https://user-images.githubusercontent.com/54086974/88278863-adac9f00-cd15-11ea-92bb-c84379fdcf6c.PNG)

**Comment by themonstrousdev** [comment]
Duplicate Issue: https://github.com/kennCK/tinabangay/issues/89
