### ISSUE TITLE
Home page typographic error

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#70]
![Capture1](https://user-images.githubusercontent.com/54056737/88353095-6e6a6680-cd86-11ea-89d6-421a497ffb60.PNG)

**Comment by PN25-RicaChristine** [comment]
@rLaurentePn2k19  changes not yet already online

**Comment by rLaurentePn2k19** [comment]
> @rLaurentePn2k19 changes not yet already online

I'll let Ken know about this.

**Comment by PN25-RicaChristine** [comment]
changes already on live
