### ISSUE TITLE
Auto logged out without logging out (back to home page)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#71]
![image](https://user-images.githubusercontent.com/54056737/88353379-6f4fc800-cd87-11ea-86d3-443273c47834.png)

1. Logged in to the website but when there's an internet interruption (internet lost) and when the internet comes back the website goes back to the home page (it logs out, so you need to log in again to use the web app).
2.  Logged in to the website but goes back to the home page if not use for a longer period of time (it logs out, so you need to log in again to use the web app). [**Encountered these issue by opening two different browser user and logged in to the website into  each user.**  ]

**Comment by PN25-RicaChristine** [comment]
Encountered 2nd issue twice already.

**Comment by rLaurentePn2k19** [comment]
Here Ken.

**Comment by rLaurentePn2k19** [comment]
- I think this is not an issue, normal ra nga mu auto logout siya when you are not doing anything on the site. The purpose of this auto logged out is for security of the user, if in case na biyaan sa usa ka User ang iya account nga naka logged in sa usa ka device or pc, then after how many minutes mo logged out ranag iya. 

- Session Destroy ni siya sa PHP or sa BackEnd side.
