### ISSUE TITLE
Add location sanitation for businesses

### ISSUE THREAD

**Issue by kennCK** [kennCK/tinabangay#75]
User story:

Business wants to add the schedule of sanitation. Sample: mwf, and ....

**Comment by Pathran-phantom1823** [comment]
Pathran-phantom1823
Soon to Work

**Comment by Pathran-phantom1823** [comment]
Almost Done
@kennCK  sir is the request of it is already merge?

**Comment by Pathran-phantom1823** [comment]
@kennCK  it's already Done
