### ISSUE TITLE
Guide Modal(No content WEB)

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#81]
This scenario happens in AGENCY_GOV, Business and Temp_Scanner Account.

![image](https://user-images.githubusercontent.com/54094859/88358438-90251700-cda1-11ea-970a-0a99d636272b.png)

![image](https://user-images.githubusercontent.com/54094859/88358473-ac28b880-cda1-11ea-972d-db0d714c26e4.png)

**Comment by GarridoL** [comment]
addressed.

**Comment by themonstrousdev** [comment]
@LGarrido0708 is this fixed bah?
