### ISSUE TITLE
BirdsEye User Guide Website Link (NOT FOUND)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#82]
This link when clicked or opened in new tab or window:
![image](https://user-images.githubusercontent.com/54056737/88358567-a6c77000-cd99-11ea-9ed5-5e1de617c10d.png)

Results to this:
![image](https://user-images.githubusercontent.com/54056737/88358598-c3fc3e80-cd99-11ea-992c-5c883833793d.png)

**Comment by GarridoL** [comment]
fixed

**Comment by PN25-RicaChristine** [comment]
This is resolved and fixed on live. Recheck already. Closing issue.
