### ISSUE TITLE
Refreshing Pages (Login and Register shows, Sidebar disappears)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#86]
**Sidebar** **disappears** as well as **Login** and **Register** **appears** when refreshing pages:
DASHBOARD:
![image](https://user-images.githubusercontent.com/54056737/88361262-a41d4880-cda2-11ea-86bd-516d320c531c.png)
MY VISITED PLACES:
![image](https://user-images.githubusercontent.com/54056737/88361308-d169f680-cda2-11ea-890b-f53c43276418.png)

**SAME WITH THE REST OF THE PAGES OF DIFFERENT ACCOUNT.**

**Comment by Pathran-phantom1823** [comment]
@themonstrousdev  this bug is due to slow connection
