### ISSUE TITLE
Notification Bell Icon Visibility

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#87]
![image](https://user-images.githubusercontent.com/54056737/88362097-77b6fb80-cda5-11ea-866e-dad26b5b9a9f.png)

_"Notification bell icon" stays hidden if there's no any notifications received (empty) but shows if there is._
CONCERN: **Leads confusion to first-time user**.
 As first time user, they will surely read on the "BirdsEye User Guide" and on the guide it is written _"Click the Bell Icon on top and you can view all your notifications from the government._" but if they're going to look at on top there's no icon. Is it better if the icon will not be hidden?

**Comment by GarridoL** [comment]
@PN25-RicaChristine Kindly check sa akong local. Salamat.

**Comment by PN25-RicaChristine** [comment]
@LGarrido0708  I already checked your local and bell icon already visible (even no notifications received)

**Comment by GarridoL** [comment]
@PN25-RicaChristine, according to Sir Ken, remain lang nga dili moshow ang icon if wala pay notifications.

**Comment by PN25-RicaChristine** [comment]
@GarridoL  okay laine copy, this issue be closed na.
