### ISSUE TITLE
Invalid Email Address Format Successfully Updated!

### ISSUE THREAD

**Issue by jeanitapaloma** [kennCK/tinabangay#89]
Module/Page: Business Settings

Module or functions: Update Button

Account Type: BUSINESS

Test Cases: Clicking "Update" button with an incorrect business e-mail 
address format and correct business name and business address. 
**Sample business email: asdf@asdf.co**

Expected Result: Invalid email address! 
Actual Results: Successfully Updated!

![concern](https://user-images.githubusercontent.com/54086853/88364025-57db0400-cdb4-11ea-9ee9-86ab83ee2e6a.PNG)

**Comment by themonstrousdev** [comment]
The checking of email only works for format, not validity. As long as it follows the string@string.end format, it will run valid. I don't believe there is a way to check if the email is actually functioning or not.

Can you confirm sir @kennCK ?

**Comment by HTundra** [comment]
The format is correct I think, kay the domain name and extension can be a lot of different things.

**Comment by jeanitapaloma** [comment]
![concern](https://user-images.githubusercontent.com/54086853/88364706-5579a980-cdb6-11ea-91f2-a0c920ba212b.PNG)
