### ISSUE TITLE
"New Place" Button gone (visited places page)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [kennCK/tinabangay#91]
**Module/Page:** My Visited Places
**Specific Feature:** New Place Button
**Test Cases:** Click "My Visited Places" tab
**Expected Results:** _New Place Button_ should appear on upper right corner below header (as shown on the video for user's guide)
![image](https://user-images.githubusercontent.com/54056737/88369036-5e1faf00-cdb9-11ea-8606-0d57f86e2eec.png)
**Actual Results:** There's **NO** _New Place Button_ .
![image](https://user-images.githubusercontent.com/54056737/88369197-b35bc080-cdb9-11ea-8a10-88934fc89eca.png)
![image](https://user-images.githubusercontent.com/54056737/88369238-cb334480-cdb9-11ea-823e-e6ad75dea871.png)

**Comment by Pathran-phantom1823** [comment]
Area is being commented, I'a,m currently asking kent

**Comment by Pathran-phantom1823** [comment]
According to kent. It is not yet allowed for the user or log new Places

**Comment by kennCK** [comment]
@themonstrousdev this is on services/auth. Ayaw lang I null
