### ISSUE TITLE
Display Encrypted Data

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#93]
Module/Page: Tracing (Agency Brgy)
Specific Feature: Display of assign address with the **date**...
Test Cases: Not applied
Expected Results: In AGENCY_GOV account type, it displays a date
Actual Results: encrypted data was shown

Also suggestion in meter radius, it could be better if we could use meters away so that lay people will understand it clearly.
![image](https://user-images.githubusercontent.com/54094859/88374717-cf1c9200-cdcc-11ea-828b-bc4474d4719e.png)

**Comment by kennCK** [comment]
@keyrwinz  kindly assign ani to other devs.
