### ISSUE TITLE
Side bar was shown while in Login Page

### ISSUE THREAD

**Issue by jalandoni** [kennCK/tinabangay#94]
Module/Page: Login Page
Specific Feature: Login
Test Cases: Clicking Login Button again after session was expired. 
Expected Results: Redirecting to login page
Actual Results: The side bar was shown as well.
Supporting File: 
![image](https://user-images.githubusercontent.com/54094859/88376170-78fd1e00-cdcf-11ea-9be8-7f0f4d1dcbc4.png)

**Comment by kennCK** [comment]
This is noted.

**Comment by Pathran-phantom1823** [comment]
@kennCK, and others, this bug is cause due to slow loading of page, what if  instead of showing the page content while loading, we just show a white background with the lodash before they can see the page content

**Comment by kennCK** [comment]
I'm on int as sa admin ni sya
