### ISSUE TITLE
No alert when scanning positive user

### ISSUE THREAD

**Issue by HTundra** [kennCK/tinabangay#95]
Scanned positive user with the following accounts:

positiveUser - positive user
employeeuser4 - scanner
businessuser2 - linked account
No alert was given to businessuser2
(The notification is an HDF notification, not the alert)
![noAlert](https://user-images.githubusercontent.com/58643990/88445664-9b864a00-ce56-11ea-9851-325c8b453f1c.png)

**Comment by kennCK** [comment]
@keyrwinz  kindly help other developer ani
