### ISSUE TITLE
Redesign Dashboard per user type

### ISSUE THREAD

**Issue by themonstrousdev** [kennCK/tinabangay#97]
**Module/Page:** 
Dashboard

**Specific Feature:**
Printed content

**Expected Results:**
1. User Type
   _Includes:_ USER, TEMP_SCANNER, DRIVER, AGENCY_TEST_MNGT, AGENCY_TEMPT_MNGT

- Prioritize showing their QR code as well as "Scan QR" button
- "Affected places" should only show top 5 affected places in their barangay/city
- prompt them for a daily symptom health check
- This has already been started. Please check User.vue in modules/dashboard

2. Business/Brgy/LGU Type
  _Includes:_ AGENCY_BRGY, BUSINESS, AGENCY_GOV, AGENCY_DOH

- No need to show their QR code
- Prioritize office information and "Scan QR" button
- show internal information on dashboard such as: affected branches/purok, total number of affected employees (linked accounts)
- Use graphs

**Comment by themonstrousdev** [comment]
There is more to be added in the business dashboard. Please contact me, Elle, when you're working on this.

**Comment by GarridoL** [comment]
User Type done. Bargaso is currently working on the business dashboard.
